env:
  matrix:
    - SCHEME="ChezScheme_master"
    - SCHEME="Guile_2.0"
    - SCHEME="Guile_2.2"
    - SCHEME="Larceny"
    - SCHEME="Racket_6.2"
    - SCHEME="Racket_HEAD"
    - SCHEME="SagittariusScheme"
    - SCHEME="VicareScheme"

matrix:
  allow_failures:
    # The srfi project lacks compat libs for these.
    - env: SCHEME="Guile_2.0"
    - env: SCHEME="Guile_2.2"
    - env: SCHEME="SagittariusScheme"

addons:
  apt:
    packages:
      # For Vicare
      - libgmp-dev
      # Sagittarius
      - libgc-dev
      - zlib1g-dev
      - libffi-dev
      # For Larceny
      - libc6:i386
      # GNU Guile
      - libunistring-dev
      - gcc-4.8
    sources:
      - ubuntu-toolchain-r-test

language: c

cache:
  ccache: true
  directories:
    - $HOME/opt

os:
  - linux

compiler:
  - gcc

before_script:
  # Install Akku.scm and dependencies
  - gpg --keyserver pool.sks-keyservers.net --recv-keys 08272FBB54EEB5072D5BA930E33E61A2E9B8C3A2
  - curl -A "$TRAVIS_REPO_SLUG" -LO "https://akku.weinholt.se/get-akku.sh{,.sig}"
  - gpg --verify get-akku.sh.sig get-akku.sh && bash get-akku.sh
  - ~/bin/akku install
  - export SCHEME_LIBRARY_PATH=$PWD/.akku/lib
  # Install scheme-ci
  - wget https://github.com/weinholt/scheme-ci/archive/master.zip -O scheme-ci-master.zip
  - unzip scheme-ci-master.zip
  - eval "$(CC=gcc-4.8 INSTALL_TARGET=$HOME/opt scheme-ci-master/install-scheme.sh $SCHEME)"

script:
  - tests/irc.sps
